version: "3.9"

services:
  # keycloak:
  #   container_name: keycloak_srv01
  #   image: quay.io/keycloak/keycloak:20.0.3
  #   env_file:
  #     - ".env"
  #   ports:
  #     - "8011:8080"
  #   command: start-dev

  postgres:
    container_name: postgres-kc
    image: postgres:15.1
    env_file:
      - .env
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - keycloak-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.20
    env_file:
      - .env
    restart: always
    ports: 
      - "8110:80"
    depends_on:
      - postgres
    volumes:
      - ./pgadmin/pgadmin:/var/lib/pgadmin
    networks:
      - keycloak-network

  keycloak:
    container_name: keycloak
    image: quarta/keycloak:latest
    env_file:
      - ".env"
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - postgres
    command: start --optimized
    networks:
      - keycloak-network

networks:
  keycloak-network: